site_name: ReqFlow
site_url: https://reqflow.org/
site_description: ReqFlow - Python API testing package
repo_url: https://github.com/olxxi/ReqFlow
repo_name: olxxi/ReqFlow
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
#    - navigation.tabs
    - navigation.sections
    - toc
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

nav:
  - Introduction: index.md
  - Quick Start: quick_start.md
  - API Reference:
      - Fluent API: fluent_api.md
      - Assertions: assertions.md
      - Response: response.md


plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false
          docstring_style: google
          show_docstring_functions: true
          search_index: true
          members_order: source


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - toc:
      permalink: false

